language: go
go:
  - 1.2.2
install:
  - go get -v code.google.com/p/go.tools/cmd/vet
  - go get -v github.com/tools/godep
  - go get -v github.com/onsi/ginkgo/ginkgo
script:  bin/test --compilers=2
branches:
  only:
  - master
